version: '2.4'
services:
  ofelia:
    container_name: ofelia
    image: mcuadros/ofelia:latest
    restart: always
    command: daemon --docker
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

  stopwatcher:
    container_name: stopwatcher
    build: ./stopwatcher
    tty: true
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./stopwatcher/config/:/usr/src/app/config/
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.stopwatcher.schedule: "@every 12h"
      ofelia.job-exec.stopwatcher.command: "python3 stop_watcher.py"
    depends_on: 
      - rocketdb
    networks:
        - default
